version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: docker
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - ./.demo/test_data.sql:/docker-entrypoint-initdb.d/test_data.sql

  sharedexpense:
    image: sharedexpense
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      DB_URL: "jdbc:postgresql://host.docker.internal:5432/postgres"
      DB_PASSWORD: docker
      DB_USER: postgres
      JWT_SECRET: 'ultra-secure-maximum-super-secret-secret'
