create table expenses_group (group_id int8 generated by default as identity, group_title varchar(255) not null, primary key (group_id));

INSERT INTO public.expenses_group (group_id, group_title) VALUES (100, 'Test group 0');
INSERT INTO public.expenses_group (group_id, group_title) VALUES (101, 'Test group 1');